/*
 Navicat Premium Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 80015
 Source Host           : localhost:3306
 Source Schema         : filmcomment1216

 Target Server Type    : MySQL
 Target Server Version : 80015
 File Encoding         : 65001

 Date: 17/12/2020 14:07:11
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for comments
-- ----------------------------
DROP TABLE IF EXISTS `comments`;
CREATE TABLE `comments`  (
  `cid` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NOT NULL,
  `fid` int(11) NOT NULL,
  `stars` int(255) UNSIGNED ZEROFILL DEFAULT NULL,
  `main` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `gmt_create` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`cid`) USING BTREE,
  INDEX `uid`(`uid`) USING BTREE,
  INDEX `fid`(`fid`) USING BTREE,
  CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `comments_ibfk_2` FOREIGN KEY (`fid`) REFERENCES `film` (`fid`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of comments
-- ----------------------------
INSERT INTO `comments` VALUES (1, 1, 1, 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000241, '“瑞德出狱后在便利店打工的时候，面对客人那真诚的笑容和服务，我觉得那是完全的发自内心的善意和积极，无关乎私欲或者说怕丢了工作，就只是纯粹的善待他人，或许也包括他请示老板能否上厕所的时候，但那可能只是他几十年来的习惯。\r\n\r\n海边，瑞德走向安迪时，帽子被海风吹走也没管顾，脸上露出笑容，没有语言却仿佛在说：好久没见，我的好兄弟，我没食言，你也没忘记。剩下的只有紧紧相拥和喜悦相逢的泪水。”', '2020-12-03 16:40:25');
INSERT INTO `comments` VALUES (2, 1, 1, 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, '但那可能只是他几十年来的习惯。\r\n剩下的只有紧紧相拥和喜悦相逢的泪水。”', '2020-12-05 16:40:25');

-- ----------------------------
-- Table structure for film
-- ----------------------------
DROP TABLE IF EXISTS `film`;
CREATE TABLE `film`  (
  `fid` int(11) NOT NULL AUTO_INCREMENT COMMENT '电影id',
  `filmname` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '电影名',
  `type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '类型',
  `intro` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '电影简介',
  `director` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '导演',
  `date1` date DEFAULT NULL COMMENT '上映日期',
  `score` float(10, 1) DEFAULT NULL COMMENT '评分',
  `score_people` int(11) DEFAULT NULL COMMENT '电影有多少人评分',
  `actor` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '演员表',
  `img` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '封面图片url',
  `regions` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '地区',
  PRIMARY KEY (`fid`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 131 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of film
-- ----------------------------
INSERT INTO `film` VALUES (1, '肖申克的救赎', '剧情', '一场谋杀案使银行家安迪（蒂姆•罗宾斯 Tim Robbins 饰）蒙冤入狱，谋杀妻子及其情人的指控将囚禁他终生。在肖申克监狱的首次现身就让监狱“大哥”瑞德（摩根•弗里曼 Morgan Freeman 饰）对他另眼相看。瑞德帮助他搞到一把石锤和一幅女明星海报，两人渐成患难 之交。', '弗兰克·德拉邦特', '1994-09-10', 9.7, 1000, '蒂姆·罗宾斯 / 摩根·弗里曼 / 鲍勃·冈顿 / 威廉姆·赛德勒 / 克兰西·布朗', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p480747492.webp', '美国');
INSERT INTO `film` VALUES (2, '霸王别姬', '剧情', '段小楼（张丰毅）与程蝶衣（张国荣）是一对打小一起长大的师兄弟，两人一个演生，一个饰旦，一向配合天衣无缝，尤其一出《霸王别姬》，更是誉满京城，为此，两人约定合演一辈子《霸王别姬》。但两人对戏剧与人生关系的理解有本质不同，段小楼深知戏非人生，程蝶衣则是人戏不分。', '陈凯歌', '1993-01-01', 8.6, 1200, '张国荣 / 张丰毅 / 巩俐 / 葛优 / 英达', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2561716440.webp', '中国大陆');
INSERT INTO `film` VALUES (3, '死亡诗社', '犯罪', '威尔顿预备学院以其沉稳凝重的教学风格和较高的升学率闻名，作为其毕业班的学生，理想就是升入名校。新学期文学老师约翰·基汀（罗宾·威廉姆斯 饰）的到来如同一阵春风，一反传统名校的严肃刻板。', '彼得·威尔', '1989-06-02', 9.7, 680, ' 罗宾·威廉姆斯 / 罗伯特·肖恩·莱纳德 / 伊桑·霍克 / 乔西·查尔斯 / 盖尔·汉森', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2575465690.webp', '美国');
INSERT INTO `film` VALUES (5, '控方证人', '剧情', '伦敦著名刑案辩护律师韦菲爵士（查尔斯•劳顿 Charles Laughton 饰）接受了心脏病治疗，但是身体依旧虚弱，第一天回家休养，护士一直严厉监督他服药，并杜绝烟酒。管家为了便于上楼，还专门为他修了电梯。但是，种种关心照顾，对于这位桀骜不驯、牙尖嘴利的大律师根本不起作用，反倒是一纸诉状令他倍感兴奋。', '比利·怀德', '1957-12-17', 9.6, 870, ' 泰隆·鲍华 / 玛琳·黛德丽 / 查尔斯·劳顿 / 爱尔莎·兰切斯特 / 约翰·威廉姆斯', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p1505392928.webp', '美国');
INSERT INTO `film` VALUES (6, '伊丽莎白', '剧情', 'A musical chronicle on the unhappy life of Empress Elisabeth of Austria and her bizarre love affair with Death.', '谢卡尔·卡普尔', '1998-10-02', 9.6, 990, ' 凯特·布兰切特 / 杰弗里·拉什 / 克里斯托弗·埃克莱斯顿 / 约瑟夫·费因斯 / 理查德·阿滕伯勒', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2264336223.webp', '奥地利');
INSERT INTO `film` VALUES (7, '阿甘正传', '剧情', '阿甘（汤姆·汉克斯 饰）于二战结束后不久出生在美国南方阿拉巴马州一个闭塞的小镇，他先天弱智，智商只有75，然而他的妈妈是一个性格坚强的女性，她常常鼓励阿甘“傻人有傻福”，要他自强不息。\r\n　　阿甘像普通孩子一样上学，并且认识了一生的朋友和至爱珍妮（罗宾·莱特·潘 饰），在珍妮 和妈妈的爱护下，阿甘凭着上帝赐予的“飞毛腿”开始了一生不停的奔跑。', '罗伯特·泽米吉斯', '1994-06-23', 9.5, 1300, '汤姆·汉克斯 / 罗宾·怀特 / 加里·西尼斯 / 麦凯尔泰·威廉逊 / 莎莉·菲尔德', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2372307693.webp', '美国');
INSERT INTO `film` VALUES (8, '美丽人生', '剧情', '犹太青年圭多（罗伯托·贝尼尼）邂逅美丽的女教师多拉（尼可莱塔·布拉斯基），他彬彬有礼的向多拉鞠躬：“早安！公主！”。历经诸多令人啼笑皆非的周折后，天遂人愿，两人幸福美满的生活在一起。', '罗伯托·贝尼尼', '2020-01-03', 9.5, 600, ' 罗伯托·贝尼尼 / 尼可莱塔·布拉斯基 / 乔治·坎塔里尼 / 朱斯蒂诺·杜拉诺 / 赛尔乔·比尼·布斯特里克', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2578474613.webp', '意大利');
INSERT INTO `film` VALUES (9, '辛德勒的名单', '剧情', '1939年，波兰在纳粹德国的统治下，党卫军对犹太人进行了隔离统治。德国商人奥斯卡·辛德勒（连姆·尼森 Liam Neeson 饰）来到德军统治下的克拉科夫，开设了一间搪瓷厂，生产军需用品。凭着出众的社交能力和大量的金钱，辛德勒和德军建立了良好的关系，他的工厂雇用犹太人工作，大发战争财。', '史蒂文·斯皮尔伯格', '1993-11-30', 9.5, 500, ' 连姆·尼森 / 本·金斯利 / 拉尔夫·费因斯 / 卡罗琳·古多尔 / 乔纳森·萨加', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p492406163.webp', '美国');
INSERT INTO `film` VALUES (10, '茶馆', '剧情', '世纪之交，古老的中国正迎来前所未有的巨大变革。老态龙钟的大清王朝摇摇欲坠，六君子的鲜血无法阻止历史车轮的滚动，老北京城的上空风云变幻，波谲云诡。王利发（于是之 饰），北京城内裕泰茶馆的年轻掌柜。他谨记父亲的教诲，体面周全地迎送四方宾客。小小的茶馆内，三教九流各色人等穿梭于此：提笼架鸟哀叹时运的松二爷（黄宗洛 饰）；慨叹国之将亡的刚毅满人常四爷（郑榕 饰）；一心谋求实业救国的秦仲义（蓝天野 饰）', '谢添', '1982-07-23', 9.5, 600, ' 于是之 / 郑榕 / 蓝天野 / 英若诚 / 黄宗洛', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2262122096.webp', '中国大陆');
INSERT INTO `film` VALUES (12, '十二怒汉（电视版）', '剧情', 'This production of \'Twelve Angry Men\', written especially for Studio One, is shorter than the film version and leaves a few twists and turns of plot undeveloped, but it is fifty minutes of class nevertheless.', '富兰克林·沙夫纳', '1954-09-20', 9.5, 650, '罗伯特·卡明斯 / 法兰奇·汤恩 / 爱德华·阿诺德 / 保罗·哈特曼 / 约翰·贝尔', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2153875961.webp', '美国');
INSERT INTO `film` VALUES (13, '这个杀手不太冷', '剧情', '里昂（让·雷诺饰）是名孤独的职业杀手，受人雇佣。一天，邻居家小姑娘马蒂尔达（纳塔丽·波特曼饰)敲开他的房门，要求在他那里暂避杀身之祸。原来邻居家的主人是警方缉毒组的眼线，只因贪污了一小包毒品而遭恶警（加里·奥德曼饰）杀害全家的惩罚。马蒂尔达得到里昂的留救，幸免于难，并留在里昂那里。里昂教小女孩使枪，她教里昂法文，两人关系日趋亲密，相处融洽。', '吕克·贝松', '1994-09-14', 9.4, 1200, '让·雷诺 / 娜塔莉·波特曼 / 加里·奥德曼 / 丹尼·爱罗 / 彼得·阿佩尔', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p511118051.webp', '法国');
INSERT INTO `film` VALUES (14, '千与千寻', '剧情', '千寻和爸爸妈妈一同驱车前往新家，在郊外的小路上不慎进入了神秘的隧道——他们去到了另外一个诡异世界—一个中世纪的小镇。远处飘来食物的香味，爸爸妈妈大快朵颐，孰料之后变成了猪！这时小镇上渐渐来了许多样子古怪、半透明的人。', '宫崎骏', '2019-06-21', 9.4, 900, '柊瑠美 / 入野自由 / 夏木真理 / 菅原文太 / 中村彰男', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2557573348.webp', '日本');
INSERT INTO `film` VALUES (15, '泰坦尼克号', '剧情', '1912年4月10日，号称 “世界工业史上的奇迹”的豪华客轮泰坦尼克号开始了自己的处女航，从英国的南安普顿出发驶往美国纽约。富家少女罗丝（凯特•温丝莱特）与母亲及未婚夫卡尔坐上了头等舱；另一边，放荡不羁的少年画家杰克（莱昂纳多·迪卡普里奥）也在码头的一场赌博中赢得了下等舱的船票。', '詹姆斯·卡梅隆', '1998-04-03', 9.4, 1350, '莱 莱昂纳多·迪卡普里奥 / 凯特·温丝莱特 / 比利·赞恩 / 凯西·贝茨 / 弗兰西丝·费舍', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p457760035.webp', '美国');
INSERT INTO `film` VALUES (16, '忠犬八公的故事', '剧情', '八公（Forest 饰）是一条谜一样的犬，因为没有人知道它从哪里来。教授帕克（理查·基尔 Richard Gere 饰）在小镇的火车站拣到一只走失的小狗，冥冥中似乎注定小狗和帕克教授有着某种缘分，帕克一抱起这只小狗就再也放不下来，最终，帕克对小狗八公的疼爱感化了起初极力反对养狗的妻子卡特（琼·艾伦 Joan Allen 饰）。', '拉斯·霍尔斯道姆', '2009-06-13', 9.4, 600, ' 理查·基尔 / 萨拉·罗默尔 / 琼·艾伦 / 罗比·萨布莱特 / 艾瑞克·阿瓦利', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p524964039.webp', '美国');
INSERT INTO `film` VALUES (17, '十二怒汉', '剧情', '一个在贫民窟长大的18岁少年因为涉嫌杀害自己的父亲被告上法庭，证人言之凿凿，各方面的证据都对他极为不利。十二个不同职业的人组成了这个案件的陪审团，他们要在休息室达成一致的意见，裁定少年是否有罪，如果罪名成立，少年将会被判处死刑。', '西德尼·吕美特', '1957-04-13', 9.4, 500, '亨利·方达 / 马丁·鲍尔萨姆 / 约翰·菲德勒 / 李·科布 / E.G.马绍尔', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2173577632.webp', '美国');
INSERT INTO `film` VALUES (18, '泰坦尼克号 3D版', '剧情', '1912年4月10日，号称 “世界工业史上的奇迹”的豪华客轮泰坦尼克号开始了自己的处女航，从英国的南安普顿出发驶往美国纽约。富家少女罗丝（凯特•温丝莱特）与母亲及未婚夫卡尔坐上了头等舱；另一边，放荡不羁的少年画家杰克（莱昂纳多·迪卡普里奥）也在码头的一场赌博中赢得了下等舱的船票。', 'Shane Van Dyke', '2010-08-24', 9.4, 900, 'Shane Van Dyke / Marie Westbrook / Bruce Davison / Brooke Burns / Michelle Glavan', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p1408665952.webp', '美国');
INSERT INTO `film` VALUES (19, '憨豆先生精选辑', '喜剧', '憨豆先生精选辑 The Best Bits of Mr. Bean (1997)', 'John Birkin / 约翰·霍华德·戴维斯', '1997-03-28', 9.6, 500, '罗温·艾金森 / 保罗·布朗 / 理查德·布赖尔斯 / Angus Deayton / 罗宾·德里斯科尔', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2354179225.webp', '英国');
INSERT INTO `film` VALUES (20, '美丽人生', '剧情', '犹太青年圭多（罗伯托·贝尼尼）邂逅美丽的女教师多拉（尼可莱塔·布拉斯基），他彬彬有礼的向多拉鞠躬：“早安！公主！”。历经诸多令人啼笑皆非的周折后，天遂人愿，两人幸福美满的生活在一起。', '德里安·布洛迪 / 托马斯·克莱舒曼 / 艾米莉娅·福克斯 / 米哈乌·热布罗夫斯基 / 埃德·斯托帕德 ', '2020-01-03', 9.5, 800, '罗伯托·贝尼尼 / 尼可莱塔·布拉斯基 / 乔治·坎塔里尼 / 朱斯蒂诺·杜拉诺 / 赛尔乔·比尼·布斯特里克', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2578474613.webp', '意大利');
INSERT INTO `film` VALUES (22, '黄子华之金盆玉口', '喜剧', '黃子華棟篤笑之金盤', '黄子华', '2018-07-06', 9.5, 600, '黄子华', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2527089368.webp', '中国香港');
INSERT INTO `film` VALUES (23, '极品基老伴：完结篇', '喜剧', '极品基老伴：完结篇 Vicious Series Finale (2016)', '埃德·拜', '2016-06-19', 9.4, 560, '伊恩·麦克莱恩 / 德里克·雅各比 / 弗朗西斯·德·拉·图瓦 / 伊万·瑞恩 / 玛西娅·沃伦 ', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2509440210.webp', '英国');
INSERT INTO `film` VALUES (24, '拽妹黛薇儿要上大学了没', '剧情', 'Graduation is looming and the seniors of Lawndale High are busy with college preparations. ', 'Karen Disher', '2002-01-21', 9.4, 650, 'Geoffrey Arend ... Charles \'Upchuck\' Ruttheimer III (voice) / Tracy Grandstaff ... Daria Morgendorffer (voice) / Rand Bridges ... Professor Bill Woods (voice) (as H.R. Bridges)', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2529714509.webp', '美国');
INSERT INTO `film` VALUES (25, '鬼子来了', '剧情', '第二次世界大战期间，中国河北挂甲台村的农民马大三（姜文饰）在日本人的统治下过着平静的生活。一个晚上，游击队绑架了日军陆军士兵花屋小三郎（香川照之饰）和翻译董汉臣，把他们捆绑塞入麻袋放在马大三家里，并吩咐马好好看管，几天后的大年三十来带人。', '姜文', '2000-05-12', 9.3, 600, '姜文 / 香川照之 / 袁丁 / 姜宏波 / 丛志军', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2553104888.webp', '中国大陆');
INSERT INTO `film` VALUES (26, '摩登时代', '剧情', '二十年代的美国处于经济萧条时期，失业率居高不下，工人受尽压榨，成为了大机器生产中的一颗螺丝钉。查理（查理·卓别林 Charles Chaplin 饰）就是一个底层市民，他在一个机器隆隆的厂房里日以继夜地工作，以赚取微薄的收入。重复繁重的工作压得他喘不过气，他把人们的鼻子当成螺丝钉来拧，卷入流水线机器的皮带里，令人苦笑不得。', '查理·卓别林', '1936-02-25', 9.3, 850, '查理·卓别林 / 宝莲·高黛 / 亨利·伯格曼 / 蒂尼·桑福德 / 切斯特·康克林 ', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2263408369.webp', '美国');
INSERT INTO `film` VALUES (27, '城市之光', '喜剧', '他是一个流浪汉（查理·卓别林 Charles Chaplin 饰），身无分文，遇上了双目失明的卖花女，却不忍袖手旁观。他想尽办法去凑够费用，供卖花女治病。一天，他搭救了一个富翁，富翁当晚和他称兄道弟，第二天却翻脸不认人。本来打算向他求助的主意行不通了。流浪汉去参加拳击比 赛，以图获得奖金，却输得一败涂地。', '查理·卓别林', '1931-01-30', 9.3, 800, '查理·卓别林 / 弗吉尼亚·切瑞尔 / 佛罗伦斯·李 / 亨利·伯格曼 / 珍·哈露', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2170238828.webp', '美国');
INSERT INTO `film` VALUES (28, '丹尼尔·斯洛斯：现场表演', '喜剧', 'The dark mind of Daniel Sloss is back, and he\'s ready to find the funny in some very taboo topics, from the deeply personal to the highly irreverent.', '丹尼尔·斯洛斯', '2018-09-11', 9.3, 650, '丹尼尔·斯洛斯', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2536540213.webp', '美国');
INSERT INTO `film` VALUES (29, '西蒙·阿姆斯特尔：顺其自然', '喜剧', '西蒙·阿姆斯特尔：顺其自然 Simon Amstell: Do Nothing (2010)', 'Michael Matheson', '2010-03-14', 9.3, 840, '西蒙·阿姆斯特尔', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2184490255.webp', '英国');
INSERT INTO `film` VALUES (30, '迪兰·莫兰：脱身', '喜剧', '迪兰·莫兰：脱身 Dylan Moran: Off the Hook (2015)', 'John Gordillo', '2015-11-30', 9.3, 630, '迪兰·莫兰', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2298274199.webp', '英国');
INSERT INTO `film` VALUES (31, '跳出我天地音乐剧', '剧情', '跳出我天地音乐剧 Billy Elliot the Musical (2014)', '史蒂芬·戴德利', '2014-09-28', 9.3, 450, 'Elliott Hanna / 鲁茜·亨肖 / Deka Walmsley / Ann Emery / Chris Grahamson ', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2215874393.webp', '英国');
INSERT INTO `film` VALUES (32, '三傻大闹宝莱坞', '剧情', '本片根据印度畅销书作家奇坦·巴哈特（Chetan Bhagat）的处女作小说《五点人》（Five Point Someone）改编而成。法兰（马德哈万 R Madhavan 饰）、拉杜（沙曼·乔希 Sharman Joshi 饰）与兰乔（阿米尔·汗 Aamir Khan 饰）是皇家工程学院的学生，三人共居一室，结为好友。', '拉吉库马尔·希拉尼', '2011-12-08', 9.2, 550, '阿米尔·汗 / 卡琳娜·卡普尔 / 马达范 / 沙尔曼·乔希 / 奥米·瓦依达 ', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p579729551.webp', '印度');
INSERT INTO `film` VALUES (33, '疯狂动物城', '喜剧', '故事发生在一个所有哺乳类动物和谐共存的美好世界中，兔子朱迪（金妮弗·古德温 Ginnifer Goodwin 配音）从小就梦想着能够成为一名惩恶扬善的刑警，凭借着智慧和努力，朱迪成功的从警校中毕业进入了疯狂动物城警察局，殊不知这里是大型肉食类动物的领地，作为第一只，也是唯一的小型食草类动物，朱迪会遇到怎样的故事呢？', '拜伦·霍华德 / 瑞奇·摩尔 / 杰拉德·布什', '2016-03-04', 9.2, 600, '金妮弗·古德温 / 杰森·贝特曼 / 伊德里斯·艾尔巴 / 珍妮·斯蕾特 / 内特·托伦斯', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2614500649.webp', '美国');
INSERT INTO `film` VALUES (46, '美丽人生', '剧情', '犹太青年圭多（罗伯托·贝尼尼）邂逅美丽的女教师多拉（尼可莱塔·布拉斯基），他彬彬有礼的向多拉鞠躬：“早安！公主！”。历经诸多令人啼笑皆非的周折后，天遂人愿，两人幸福美满的生活在一起。', '德里安·布洛迪 / 托马斯·克莱舒曼 / 艾米莉娅·福克斯 / 米哈乌·热布罗夫斯基 / 埃德·斯托帕德 ', '2020-01-03', 9.5, 500, '罗伯托·贝尼尼 / 尼可莱塔·布拉斯基 / 乔治·坎塔里尼 / 朱斯蒂诺·杜拉诺 / 赛尔乔·比尼·布斯特里克', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2578474613.webp', '意大利');
INSERT INTO `film` VALUES (47, '辛德勒的名单', '剧情', '1939年，波兰在纳粹德国的统治下，党卫军对犹太人进行了隔离统治。德国商人奥斯卡·辛德勒（连姆·尼森 Liam Neeson 饰）来到德军统治下的克拉科夫，开设了一间搪瓷厂，生产军需用品。凭着出众的社交能力和大量的金钱，辛德勒和德军建立了良好的关系，他的工厂雇用犹太人工作，大发战争财。', '史蒂文·斯皮尔伯格', '1993-11-30', 9.5, 450, '连姆·尼森 / 本·金斯利 / 拉尔夫·费因斯 / 卡罗琳·古多尔 / 乔纳森·萨加尔 ', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p492406163.webp', '美国');
INSERT INTO `film` VALUES (48, '黎明到来', '战争', '电影根据真实故事改编。描写以杰克·布森、阿斯特丽德、凯尔·维尧姆为首的丹麦抵抗组织战士，在德国占领下丹麦的最后一天里与侵略者战斗的故事', '斯文·梅斯林', '1955-02-17', 9.4, 550, ' John Wittig / 阿斯特丽兹·维尧姆 / Svend Methling / Kjeld Jacobsen / Karl Striebeck', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2538684485.webp', '丹麦');
INSERT INTO `film` VALUES (49, '乱世佳人', '剧情', '美国南北战争前夕，南方农场塔拉庄园的千金斯嘉丽（费雯·丽 Vivien Leigh 饰）爱上了另一个农场主的儿子艾希礼（莱斯利·霍华德 Leslie Howard 饰），遭到了拒绝，为了报复，她嫁给了自己不爱的男人，艾希礼妻子梅兰妮（奥利维娅·德哈维兰 Olivia de Havilland 饰）的弟弟查尔斯。', '维克多·弗莱明 / 乔治·库克 / 山姆·伍德', '1939-12-15', 9.3, 650, '玛格丽特·米歇尔 / 西德尼·霍华德 / 奥利弗·H·P·加勒特 / 本·赫克特 / 乔·斯沃林 / 约翰·范·德鲁登', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p1963126880.webp', '美国');
INSERT INTO `film` VALUES (50, '钢琴家', '剧情', '史标曼（艾德里安•布洛迪 Adrien Brody 饰）是波兰一家电台的钢琴师。二战即将爆发之时，他们全家被迫被赶进华沙的犹太区。在战争的颠沛流离中，家人和亲戚最终被纳粹杀害，而标曼本人也受尽种种羞辱和折磨，他侥幸得到一位朋友的帮助，暂时有了藏身之处。', '罗曼·波兰斯基', '2002-05-24', 9.2, 800, '德里安·布洛迪 / 托马斯·克莱舒曼 / 艾米莉娅·福克斯 / 米哈乌·热布罗夫斯基 / 埃德·斯托帕德 ', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p792376093.webp', '法国');
INSERT INTO `film` VALUES (51, '地下', '剧情', '影片通过三位主人公——知识分子和投机商马高、他的朋友黑仔、他们共同的爱人娜塔莉——传奇般的人生展现了导演对南斯拉夫这个民族的理解与复杂情感。', '埃米尔·库斯图里卡', '1995-04-01', 9.2, 650, '米基·马诺伊洛维奇 / 拉扎尔·里斯托夫斯基 / 米里亚娜·约科维奇 / 斯拉夫科·斯提马科 / 恩斯特·施托兹', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p1833776334.webp', '南斯拉夫');
INSERT INTO `film` VALUES (52, '你逃我也逃', '喜剧', '波兰华沙有一个剧团，其中有一名演员Bronski（Tom Dugan 饰）极其擅长模仿德国纳粹领袖希特勒。Maria Tura（卡洛·朗白 Carole Lombard 饰）和Joseph Tura（杰克·本尼 Jack Benny 饰）是剧团里的一对夫妻，剧团最近正在上演《哈姆雷特》。', '恩斯特·刘别谦', '1942-03-06', 9.2, 450, '卡洛·朗白 / 杰克·本尼 / 罗伯特·斯塔克 / 菲利克斯·布雷萨特 / 莱昂内尔·阿特威尔', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p1339915772.webp', '美国');
INSERT INTO `film` VALUES (53, '辛德勒的名单', '历史', '1939年，波兰在纳粹德国的统治下，党卫军对犹太人进行了隔离统治。德国商人奥斯卡·辛德勒（连姆·尼森 Liam Neeson 饰）来到德军统治下的克拉科夫，开设了一间搪瓷厂，生产军需用品。凭着出众的社交能力和大量的金钱，辛德勒和德军建立了良好的关系，他的工厂雇用犹太人工作，大发战争财。', '史蒂文·斯皮尔伯格', '1993-11-30', 9.5, 450, '连姆·尼森 / 本·金斯利 / 拉尔夫·费因斯 / 卡罗琳·古多尔 / 乔纳森·萨加尔 ', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p492406163.webp', '美国');
INSERT INTO `film` VALUES (54, '茶馆', '历史', '世纪之交，古老的中国正迎来前所未有的巨大变革。老态龙钟的大清王朝摇摇欲坠，六君子的鲜血无法阻止历史车轮的滚动，老北京城的上空风云变幻，波谲云诡。王利发（于是之 饰），北京城内裕泰茶馆的年轻掌柜。他谨记父亲的教诲，体面周全地迎送四方宾客。小小的茶馆内，三教九流各色人等穿梭于此：提笼架鸟哀叹时运的松二爷（黄宗洛 饰）；慨叹国之将亡的刚毅满人常四爷（郑榕 饰）；一心谋求实业救国的秦仲义（蓝天野 饰）', '谢添', '1982-03-14', 9.5, 300, '于是之 / 郑榕 / 蓝天野 / 英若诚 / 黄宗洛', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2262122096.webp', '中国大陆');
INSERT INTO `film` VALUES (55, '横空出世', '历史', '1949年新中国建立以来，虽然人民当家做主人，但是新政权还随时面临被海外敌对势力所颠覆的严峻现状。惨烈的抗美援朝战争结束后，曾经立下赫赫战功的冯石将军（李雪健 饰）接到中央委派的重要使命，那就是主持原子弹的研发工作。', '陈国星', '1999-12-12', 9.4, 650, '李雪健 / 李幼斌 / 高明 / 陈瑾 / 滕汝骏', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p672536444.webp', '中国大陆');
INSERT INTO `film` VALUES (56, '活着', '历史', '根据余华同名小说改编。\r\n　　富少福贵（葛优）嗜赌成性，妻子家珍（巩俐）屡劝无果后带着女儿凤霞离开了他，当夜，福贵输光所有家产气死父亲，被迫靠变卖母亲首饰租间破屋过活。一年后，家珍手拉凤霞怀抱刚出世的儿子有庆回到家中，福贵痛改前非，开始靠演皮影戏过起安份守己的日子。', '张艺谋', '1994-06-30', 9.3, 500, '葛优 / 巩俐 / 姜武 / 牛犇 / 郭涛', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2513253791.webp', '中国大陆');
INSERT INTO `film` VALUES (57, '末代皇帝', '传记', '溥仪（尊龙 饰）的一生在电影中娓娓道来。他从三岁起登基，年幼的眼光中只有大臣身上的一只蝈蝈，江山在他心中只是一个不明所以的名词。长大了，他以为可以变革，却被太监一把烧了朝廷账本。他以为是大清江山的主人，却做了日本人的傀儡。', '贝纳尔多·贝托鲁奇', '1987-10-04', 9.3, 450, '尊龙 / 陈冲 / 邬君梅 / 彼得·奥图尔 / 英若诚', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p452089833.webp', '英国');
INSERT INTO `film` VALUES (58, '乱世佳人', '历史', '美国南北战争前夕，南方农场塔拉庄园的千金斯嘉丽（费雯·丽 Vivien Leigh 饰）爱上了另一个农场主的儿子艾希礼（莱斯利·霍华德 Leslie Howard 饰），遭到了拒绝，为了报复，她嫁给了自己不爱的男人，艾希礼妻子梅兰妮（奥利维娅·德哈维兰 Olivia de Havilland 饰）的弟弟查尔斯。', '维克多·弗莱明 / 乔治·库克 / 山姆·伍德', '1939-12-15', 9.3, 600, '费雯·丽 / 克拉克·盖博 / 奥利维娅·德哈维兰 / 托马斯·米切尔 / 芭芭拉·欧内尔', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p1963126880.webp', '美国');
INSERT INTO `film` VALUES (59, '钢琴家', '传记', '史标曼（艾德里安•布洛迪 Adrien Brody 饰）是波兰一家电台的钢琴师。二战即将爆发之时，他们全家被迫被赶进华沙的犹太区。在战争的颠沛流离中，家人和亲戚最终被纳粹杀害，而标曼本人也受尽种种羞辱和折磨，他侥幸得到一位朋友的帮助，暂时有了藏身之处。', '罗曼·波兰斯基', '2002-05-24', 9.2, 450, '艾德里安·布洛迪 / 托马斯·克莱舒曼 / 艾米莉娅·福克斯 / 米哈乌·热布罗夫斯基 / 埃德·斯托帕德', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p792376093.webp', '法国');
INSERT INTO `film` VALUES (60, '千与千寻', '动画', '千寻和爸爸妈妈一同驱车前往新家，在郊外的小路上不慎进入了神秘的隧道——他们去到了另外一个诡异世界—一个中世纪的小镇。远处飘来食物的香味，爸爸妈妈大快朵颐，孰料之后变成了猪！这时小镇上渐渐来了许多样子古怪、半透明的人。', '宫崎骏', '2019-06-21', 9.4, 900, '柊瑠美 / 入野自由 / 夏木真理 / 菅原文太 / 中村彰男', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2557573348.webp', '日本');
INSERT INTO `film` VALUES (61, '大闹天宫', '奇幻', '话说在东土傲来国有一座花果山，山上有一尊石猴吸收日精月华化身为一只神猴（邱岳峰 音），统领着山中的猴子猴孙。为求得一件称心的宝贝，神猴孙大圣潜入龙宫，强硬求来大禹治水时的定海神针如意金箍棒。东海龙王（毕克 音）心有不甘，于是上天将此事诉诸玉帝（富润生 音）。', '万籁鸣 / 唐澄', '1916-03-14', 9.3, 600, ' 邱岳峰 / 富润生 / 毕克 / 尚华 / 于鼎', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2184505167.webp', '中国大陆');
INSERT INTO `film` VALUES (62, '生活多美好', '爱情', '乔治（詹姆斯•斯图尔特 James Stewart 饰）在圣诞节前准备自杀，这时上帝传来旨意，派天使拯救他，并让他了解到自己一生的使命——拯救那些不幸的人。', '弗兰克·卡普拉', '1946-12-20', 9.3, 500, ' 詹姆斯·斯图尔特 / 唐娜·里德 / 莱昂纳尔·巴里摩尔 / 托马斯·米切尔 / 亨利·崔佛斯', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p771490367.webp', '美国');
INSERT INTO `film` VALUES (63, '狐妖小红娘剧场版：月红篇', '动画', '根据古典小说记载，世上有人有妖，妖会与人相恋，妖寿命千万年，人的寿命有限，人死了，妖活着。人会投胎转世，但投胎以后，不记得上辈子的爱。妖如果痴情的话，就去找狐妖“购买”一项服务，让投胎转世的人，回忆起前世的爱。', '王昕 / 董易', '2016-06-24', 9.3, 350, '杨天翔 / 刘校妤 / 张杰 / 张予佟 / 张凯 ', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2585323764.webp', '中国大陆');
INSERT INTO `film` VALUES (64, '大话西游之大圣娶亲', '爱情', '至尊宝（周星驰 饰）被月光宝盒带回到五百年前，遇见紫霞仙子（朱茵 饰），被对方打上烙印成为对方的人，并发觉自己已变成孙悟空。\r\n　　紫霞与青霞（朱茵 饰）本是如来佛祖座前日月神灯的灯芯（白天是紫霞，晚上是青霞），二人虽然同一肉身却仇恨颇深，因此紫霞立下誓言，谁能拔出她手中的紫青宝剑，谁就是她的意中人。', '刘镇伟', '1995-02-04', 9.2, 600, ' 周星驰 / 吴孟达 / 朱茵 / 蔡少芬 / 蓝洁瑛', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2455050536.webp', '中国香港');
INSERT INTO `film` VALUES (65, '龙猫', '奇幻', '小月的母亲生病住院了，父亲带着她与四岁的妹妹小梅到乡间的居住。她们对那里的环境都感到十分新奇，也发现了很多有趣的事情。', '宫崎骏', '2018-12-14', 9.2, 550, '日高法子 / 坂本千夏 / 糸井重里 / 岛本须美 / 北林谷荣', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2540924496.webp', '日本');
INSERT INTO `film` VALUES (66, '指环王3：王者无敌', '动作', '魔幻战争逐渐进入高潮阶段。霍比特人弗拉多（伊利亚·伍德 Elijah Wood 饰）携带着魔戒，与伙伴山姆（Sean Astin 饰）以及狡猾阴暗的咕噜等前往末日山，一路上艰难险阻不断，魔君索伦为阻止魔戒被销毁用尽全力阻挠。另一方面，白袍巫师甘道夫（伊安·麦克莱恩 Ian McKellen 饰）率中土勇士们镇守刚铎首都——白城米那斯提里斯。', '彼得·杰克逊', '2004-03-12', 9.2, 450, ' 伊利亚·伍德 / 西恩·奥斯汀 / 维果·莫腾森 / 奥兰多·布鲁姆 / 伊恩·麦克莱恩', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p1910825503.webp', '美国');
INSERT INTO `film` VALUES (67, '天书奇谭', '奇幻', '天庭有珍奇书籍“天书”，被锁在石龛门里三千年。看守天书的袁公对天书的内容好奇不已，他乘无人之际，偷偷拿出观看。原来，天书上记录了一百〇八条法术，袁公偷偷下凡，把天书上的内容刻在石壁上。但本意造福人类的袁公此举却触犯了天条，遭到了玉帝的惩罚。', '王树忱 / 钱运达', '1983-01-14', 9.2, 400, '丁建华 / 毕克 / 苏秀 / 程晓桦 / 施融 ', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2515539487.webp', '中国大陆');
INSERT INTO `film` VALUES (68, '金猴降妖', '动画', '话说齐天大圣孙悟空、天篷元帅猪八戒以及卷帘大将沙和尚保护唐僧西天取经，一路上历经千辛万苦，降服妖魔鬼怪无数。这一日，师徒四人来在一片荒山野岭之中。这时一年轻村姑上前求助，孙悟空火眼金睛认出是妖怪白骨精所化，上前将其打跑。然唐三藏肉眼凡胎，嗔怪悟空伤害性命，加上猪八戒煽风点火，紧箍咒念得齐天大圣疼痛难忍。', '特伟 / 严定宪 / 林文肖', '1985-02-01', 9.2, 300, '李扬 / 谈鹏飞 / 洪融 / 吴鲁生 / 战车', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p1988812771.webp', '中国大陆');
INSERT INTO `film` VALUES (69, '寻梦环游记', '动画', '热爱音乐的米格尔（安东尼·冈萨雷兹 Anthony Gonzalez 配音）不幸地出生在一个视音乐为洪水猛兽的大家庭之中，一家人只盼着米格尔快快长大，好继承家里传承了数代的制鞋产业。一年一度的亡灵节即将来临，每逢这一天，去世的亲人们的魂魄便可凭借着摆在祭坛上的照片返回现世和生者团圆。', '李·昂克里奇 / 阿德里安·莫利纳', '2017-11-24', 9.1, 350, '安东尼·冈萨雷斯 / 盖尔·加西亚·贝纳尔 / 本杰明·布拉特 / 阿兰娜·乌巴赫 / 芮妮·维克托', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2614500706.webp', '美国');
INSERT INTO `film` VALUES (70, '少年派的奇幻漂流', '奇幻', '故事开始于蒙特娄，也结束于蒙特娄。一名在找寻灵感的作家（拉菲·斯波 Rafe Spall 饰）无意间得知派·帕帖尔（伊尔凡·可汗 Irrfan Khan 饰）的传奇故事。派的父亲（阿迪勒·侯赛因 Adil Hussain 饰）开了一家动物园。因这样特殊的生活环境，少年派（苏拉·沙玛 Suraj Sharma 饰 ）对信仰与人的本性自有一套看法。', '李安', '2012-11-22', 9.1, 800, '苏拉·沙玛 / 伊尔凡·可汗 / 拉菲·斯波 / 阿迪勒·侯赛因 / 塔布', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p1784592701.webp', '美国');
INSERT INTO `film` VALUES (71, '哈利·波特与魔法石', '冒险', '哈利波特是一个孤儿，从小寄养在姨妈家，受尽欺凌。但就在哈利11岁生日的时候，他意外收到了霍格沃茨学院的入学通知书。哈利从该学院派来接他的巨人海格口中得知，这是一间魔法学院，并得知了自己的身世，原来哈利的父母都是伟大的魔法师，在对付伏地魔的战斗中双双献身，唯有哈利幸免于难。', '克里斯·哥伦布', '2002-01-26', 9.1, 1000, '丹尼尔·雷德克里夫 / 艾玛·沃森 / 鲁伯特·格林特 / 艾伦·瑞克曼 / 玛吉·史密斯', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2614949805.webp', '美国');
INSERT INTO `film` VALUES (73, '阿甘正传', '爱情', '阿甘（汤姆·汉克斯 饰）于二战结束后不久出生在美国南方阿拉巴马州一个闭塞的小镇，他先天弱智，智商只有75，然而他的妈妈是一个性格坚强的女性，她常常鼓励阿甘“傻人有傻福”，要他自强不息。\r\n　　阿甘像普通孩子一样上学，并且认识了一生的朋友和至爱珍妮（罗宾·莱特·潘 饰），在珍妮 和妈妈的爱护下，阿甘凭着上帝赐予的“飞毛腿”开始了一生不停的奔跑。', '罗伯特·泽米吉斯', '1994-06-23', 9.5, 1200, ' 汤姆·汉克斯 / 罗宾·怀特 / 加里·西尼斯 / 麦凯尔泰·威廉逊 / 莎莉·菲尔德', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2372307693.webp', '美国');
INSERT INTO `film` VALUES (74, '美丽人生', '喜剧', '犹太青年圭多（罗伯托·贝尼尼）邂逅美丽的女教师多拉（尼可莱塔·布拉斯基），他彬彬有礼的向多拉鞠躬：“早安！公主！”。历经诸多令人啼笑皆非的周折后，天遂人愿，两人幸福美满的生活在一起。', '罗伯托·贝尼尼', '2020-01-03', 9.5, 900, '罗伯托·贝尼尼 / 尼可莱塔·布拉斯基 / 乔治·坎塔里尼 / 朱斯蒂诺·杜拉诺 / 赛尔乔·比尼·布斯特里克', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2578474613.webp', '意大利');
INSERT INTO `film` VALUES (75, '福尔摩斯二世', '动作', '影片的男主角基顿（巴斯特·基顿 Buster Keaton 饰）是一名乡村影院电影放映师，他喜欢阅读侦探类的书籍，经常幻想自己就是一名像福尔摩斯一样的大侦探。', '巴斯特·基顿', '1924-04-21', 9.5, 560, '巴斯特·基顿 / 凯瑟琳·麦奎尔 / 乔·基顿 / Erwin Connelly / Ward Crane', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2206737207.webp', '美国');
INSERT INTO `film` VALUES (76, '泰坦尼克号', '爱情', '1912年4月10日，号称 “世界工业史上的奇迹”的豪华客轮泰坦尼克号开始了自己的处女航，从英国的南安普顿出发驶往美国纽约。富家少女罗丝（凯特•温丝莱特）与母亲及未婚夫卡尔坐上了头等舱；另一边，放荡不羁的少年画家杰克（莱昂纳多·迪卡普里奥）也在码头的一场赌博中赢得了下等舱的船票。', '詹姆斯·卡梅隆', '1998-04-03', 9.4, 1200, '莱昂纳多·迪卡普里奥 / 凯特·温丝莱特 / 比利·赞恩 / 凯西·贝茨 / 弗兰西丝·费舍', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p457760035.webp', '美国');
INSERT INTO `film` VALUES (78, '灿烂人生', '爱情', '马里奥（阿莱西奥•博尼 Alessio Boni 饰）和尼古拉（卢伊吉洛•肖卡 Luigi Lo Cascio 饰）是亲密无间的两兄弟，但是酷爱诗歌的马里奥却在考试中因为与教授意见相左而不及格，相反尼古拉投其所好的表现赢得了医学教授的好评拿到了高分。', '马可·图利奥·吉奥达纳', '2003-06-22', 9.4, 800, '路易吉·洛·卡肖 / 阿莱西奥·博尼 / 索尼娅·贝加马斯科 / 玛雅·珊萨 / 法布里齐奥·吉福尼', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p1161132422.webp', '意大利');
INSERT INTO `film` VALUES (79, '巴黎圣母院', '爱情', '善良的吉普赛女郎艾斯米拉达（海伦娜·赛加拉 Hélène Ségara 饰）天性热情奔放，就连巴黎圣母院的神父克洛德也为其倾倒。为了得到艾斯米拉达，克洛德神父指使教堂中丑陋的撞钟人卡西莫多（加劳 Garou 饰）绑架艾斯米拉达，没想到半路杀出的上尉菲比斯（帕特里克·费欧里 Patrick Fiori 饰）上演了一出英雄救美的好戏。', 'Gilles Maheu', '2018-03-14', 9.4, 600, '海伦娜·赛加拉 / 加劳 / 丹尼尔·拉沃伊 / 布鲁诺·佩尔蒂埃 / 帕特里克·费欧里', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2329626263.webp', '法国');
INSERT INTO `film` VALUES (80, '罗密欧与朱丽叶', '爱情', '凯普莱特和蒙太古是声名显赫的两大家族，因为祖先们结下恩怨，两家人将彼此视为眼中钉肉中刺。可是造化弄人，在机缘巧合之下，蒙太古家的小儿子罗密欧（达米安·萨格 Damien Sargue 饰）在一场宴会上偶遇了凯普莱特家的女儿朱丽叶（希西莉亚·卡拉 Cécilia Cara 饰），在不知道彼此身份的情况下，两人双双坠入了爱河，并且在神父的见证之下私定终身。', '巴兹·鲁赫曼', '1996-11-01', 9.4, 1000, '莱昂纳多·迪卡普里奥 / 克莱尔·丹妮丝 / 约翰·雷吉扎莫 / 哈罗德·佩里诺 / 皮特·波斯尔思韦特', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2224933614.webp', '法国');
INSERT INTO `film` VALUES (81, '乱世佳人', '历史', '美国南北战争前夕，南方农场塔拉庄园的千金斯嘉丽（费雯·丽 Vivien Leigh 饰）爱上了另一个农场主的儿子艾希礼（莱斯利·霍华德 Leslie Howard 饰），遭到了拒绝，为了报复，她嫁给了自己不爱的男人，艾希礼妻子梅兰妮（奥利维娅·德哈维兰 Olivia de Havilland 饰）的弟弟查尔斯。', '维克多·弗莱明 / 乔治·库克 / 山姆·伍德', '1939-12-15', 9.3, 950, '费雯·丽 / 克拉克·盖博 / 奥利维娅·德哈维兰 / 托马斯·米切尔 / 芭芭拉·欧内尔', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p1963126880.webp', '美国');
INSERT INTO `film` VALUES (82, '摩登时代', '喜剧', '二十年代的美国处于经济萧条时期，失业率居高不下，工人受尽压榨，成为了大机器生产中的一颗螺丝钉。查理（查理·卓别林 Charles Chaplin 饰）就是一个底层市民，他在一个机器隆隆的厂房里日以继夜地工作，以赚取微薄的收入。重复繁重的工作压得他喘不过气，他把人们的鼻子当成螺丝钉来拧，卷入流水线机器的皮带里，令人苦笑不得。', '查理·卓别林', '1936-02-25', 9.3, 650, '查理·卓别林 / 宝莲·高黛 / 亨利·伯格曼 / 蒂尼·桑福德 / 切斯特·康克林', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2263408369.webp', '美国');
INSERT INTO `film` VALUES (83, '城市之光', '剧情', '他是一个流浪汉（查理·卓别林 Charles Chaplin 饰），身无分文，遇上了双目失明的卖花女，却不忍袖手旁观。他想尽办法去凑够费用，供卖花女治病。一天，他搭救了一个富翁，富翁当晚和他称兄道弟，第二天却翻脸不认人。本来打算向他求助的主意行不通了。流浪汉去参加拳击比 赛，以图获得奖金，却输得一败涂地。', '查理·卓别林', '1931-01-30', 9.3, 500, '查理·卓别林 / 弗吉尼亚·切瑞尔 / 佛罗伦斯·李 / 亨利·伯格曼 / 珍·哈露', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2170238828.webp', '美国');
INSERT INTO `film` VALUES (84, '生活多美好', '爱情', '乔治（詹姆斯•斯图尔特 James Stewart 饰）在圣诞节前准备自杀，这时上帝传来旨意，派天使拯救他，并让他了解到自己一生的使命——拯救那些不幸的人。', '弗兰克·卡普拉', '1946-12-20', 9.3, 350, '詹姆斯·斯图尔特 / 唐娜·里德 / 莱昂纳尔·巴里摩尔 / 托马斯·米切尔 / 亨利·崔佛斯', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p771490367.webp', '美国');
INSERT INTO `film` VALUES (85, '狐妖小红娘剧场版：月红篇', '动画', '根据古典小说记载，世上有人有妖，妖会与人相恋，妖寿命千万年，人的寿命有限，人死了，妖活着。人会投胎转世，但投胎以后，不记得上辈子的爱。妖如果痴情的话，就去找狐妖“购买”一项服务，让投胎转世的人，回忆起前世的爱。', '王昕 / 董易', '2016-06-24', 9.3, 450, '杨天翔 / 刘校妤 / 张杰 / 张予佟 / 张凯', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2585323764.webp', '中国大陆');
INSERT INTO `film` VALUES (86, '末代皇帝', '传记', '溥仪（尊龙 饰）的一生在电影中娓娓道来。他从三岁起登基，年幼的眼光中只有大臣身上的一只蝈蝈，江山在他心中只是一个不明所以的名词。长大了，他以为可以变革，却被太监一把烧了朝廷账本。他以为是大清江山的主人，却做了日本人的傀儡。', '贝纳尔多·贝托鲁奇', '1987-10-04', 9.3, 300, '尊龙 / 陈冲 / 邬君梅 / 彼得·奥图尔 / 英若诚', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p452089833.webp', '英国');
INSERT INTO `film` VALUES (87, '末代皇帝', '传记', '溥仪（尊龙 饰）的一生在电影中娓娓道来。他从三岁起登基，年幼的眼光中只有大臣身上的一只蝈蝈，江山在他心中只是一个不明所以的名词。长大了，他以为可以变革，却被太监一把烧了朝廷账本。他以为是大清江山的主人，却做了日本人的傀儡。', '贝纳尔多·贝托鲁奇', '1987-10-04', 9.3, 300, '尊龙 / 陈冲 / 邬君梅 / 彼得·奥图尔 / 英若诚', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p452089833.webp', '英国');
INSERT INTO `film` VALUES (88, '世界滞在记：18岁的小栗旬在西伯利亚', '传记', '18岁的小栗旬因为对前途的迷茫参加了这次西伯利亚之旅。在冬季的贝加尔湖上凿冰钓鱼，亲手宰杀猎到的小鹿，在这里他体验到了生活的艰辛，又再次重新思考了自己的道路。08年节目组再次回访，小栗旬说某种意义上这次旅行成为了他的原点。', '小栗旬', '2009-01-09', 9.3, 550, '小栗旬', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2238186336.webp', '日本');
INSERT INTO `film` VALUES (89, '钢琴家', '传记', '史标曼（艾德里安•布洛迪 Adrien Brody 饰）是波兰一家电台的钢琴师。二战即将爆发之时，他们全家被迫被赶进华沙的犹太区。在战争的颠沛流离中，家人和亲戚最终被纳粹杀害，而标曼本人也受尽种种羞辱和折磨，他侥幸得到一位朋友的帮助，暂时有了藏身之处。', '罗曼·波兰斯基', '2002-05-24', 9.2, 450, '艾德里安·布洛迪 / 托马斯·克莱舒曼 / 艾米莉娅·福克斯 / 米哈乌·热布罗夫斯基 / 埃德·斯托帕德', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p792376093.webp', '法国');
INSERT INTO `film` VALUES (90, '南海十三郎', '传记', '开片是说书人因聚众滋事，被警察（黄霑 饰）带到了警局问话，借说书人之口讲述了粤剧金牌编剧——南海十三郎艺海浮沉的一生。作为江太史公的十三子，江誉镠（谢君豪 饰）自由顽皮，出入名流场所。一次偶然的舞会，他遇到了上海的千金小姐莉莉（吴绮莉 饰），然而双方有缘相逢，无 份结亲。后来，他跟随她来到上海，竟落得穷困潦倒。', '谢君豪', '2018-03-14', 9.2, 650, '谢君豪', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2578760496.webp', '中国香港');
INSERT INTO `film` VALUES (91, '剃头匠', '传记', '敬大爷如今是个九十三岁高龄的耄耋老人，他有八十多年的剃头经历，至今仍住在北京胡同的大杂院里，过着北京城内最底层最普通也是最平淡的生活，他经常给老主顾们上门剃头、聊天，回家后拨弄着自己那座每天慢五分钟的老座钟，他希望每个人（也包括他自己）干干净净的来到人世，也希望人们干干净净利利索索的离去……', '哈斯朝鲁', '2006-10-24', 9.2, 450, '靖奎', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2186918733.webp', '中国大陆');
INSERT INTO `film` VALUES (92, '末代皇帝', '传记', '溥仪（尊龙 饰）的一生在电影中娓娓道来。他从三岁起登基，年幼的眼光中只有大臣身上的一只蝈蝈，江山在他心中只是一个不明所以的名词。长大了，他以为可以变革，却被太监一把烧了朝廷账本。他以为是大清江山的主人，却做了日本人的傀儡。', '贝纳尔多·贝托鲁奇', '1987-10-04', 9.3, 300, '尊龙 / 陈冲 / 邬君梅 / 彼得·奥图尔 / 英若诚', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p452089833.webp', '英国');
INSERT INTO `film` VALUES (93, '世界滞在记：18岁的小栗旬在西伯利亚', '传记', '18岁的小栗旬因为对前途的迷茫参加了这次西伯利亚之旅。在冬季的贝加尔湖上凿冰钓鱼，亲手宰杀猎到的小鹿，在这里他体验到了生活的艰辛，又再次重新思考了自己的道路。08年节目组再次回访，小栗旬说某种意义上这次旅行成为了他的原点。', '小栗旬', '2009-01-09', 9.3, 250, '小栗旬', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2238186336.webp', '日本');
INSERT INTO `film` VALUES (94, '钢琴家', '传记', '史标曼（艾德里安•布洛迪 Adrien Brody 饰）是波兰一家电台的钢琴师。二战即将爆发之时，他们全家被迫被赶进华沙的犹太区。在战争的颠沛流离中，家人和亲戚最终被纳粹杀害，而标曼本人也受尽种种羞辱和折磨，他侥幸得到一位朋友的帮助，暂时有了藏身之处。', '罗曼·波兰斯基', '2002-05-24', 9.2, 450, '艾德里安·布洛迪 / 托马斯·克莱舒曼 / 艾米莉娅·福克斯 / 米哈乌·热布罗夫斯基 / 埃德·斯托帕德 ', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p792376093.webp', '法国');
INSERT INTO `film` VALUES (95, '南海十三郎', '传记', '开片是说书人因聚众滋事，被警察（黄霑 饰）带到了警局问话，借说书人之口讲述了粤剧金牌编剧——南海十三郎艺海浮沉的一生。作为江太史公的十三子，江誉镠（谢君豪 饰）自由顽皮，出入名流场所。一次偶然的舞会，他遇到了上海的千金小姐莉莉（吴绮莉 饰），然而双方有缘相逢，无 份结亲。后来，他跟随她来到上海，竟落得穷困潦倒。', '谢君豪', '2018-03-14', 9.2, 450, '谢君豪', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2578760496.webp', '中国香港');
INSERT INTO `film` VALUES (96, '剃头匠', '传记', '敬大爷如今是个九十三岁高龄的耄耋老人，他有八十多年的剃头经历，至今仍住在北京胡同的大杂院里，过着北京城内最底层最普通也是最平淡的生活，他经常给老主顾们上门剃头、聊天，回家后拨弄着自己那座每天慢五分钟的老座钟，他希望每个人（也包括他自己）干干净净的来到人世，也希望人们干干净净利利索索的离去……', '哈斯朝鲁', '2006-10-24', 9.2, 350, '靖奎', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2186918733.webp', '中国大陆');
INSERT INTO `film` VALUES (97, '演员工作室：凯文·史派西', '传记', '演员工作室：凯文·史派西 Inside the Actors Studio - Kevin Spacey (2000)', '凯文·史派西', '2000-07-02', 9.2, 450, '詹姆斯·里普顿 / 凯文·史派西', 'https://images.weserv.nl/?url=img9.doubanio.com/view/subject/l/public/s3153676.jpg', '美国');
INSERT INTO `film` VALUES (98, '当幸福来敲门', '传记', '克里斯•加纳（威尔·史密斯 Will Smith 饰）用尽全部积蓄买下了高科技治疗仪，到处向医院推销，可是价格高昂，接受的人不多。就算他多努力都无法提供一个良好的生活环境给妻儿，妻子（桑迪·牛顿 Thandie Newton 饰）最终选择离开家。从此他带着儿子克里斯托夫（贾登·史密斯 Jaden Smith 饰）相依为命。', '加布里埃莱·穆奇诺', '2008-01-17', 9.1, 350, '威尔·史密斯 / 贾登·史密斯 / 坦迪·牛顿 / 布莱恩·豪威 / 詹姆斯·凯伦 ', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2614359276.webp', '美国');
INSERT INTO `film` VALUES (99, '莫娣', '传记', '真人真事改编，描述在加拿大美丽的大西洋省份新斯科舍省（Nova Scotia），一位患有关节炎的民间艺术家莫娣·刘易斯(Maud Lewis)，对艺术不懈的追求，与她的丈夫相识，并以艺术、贩卖作品为生的励志生活。', '艾斯林·沃什', '2016-09-02', 9.1, 450, '莎莉·霍金斯 / 伊桑·霍克 / 卡瑞·玛切特 / 加布里埃尔·罗斯 / 扎卡里·贝内特', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2431089276.webp', '爱尔兰');
INSERT INTO `film` VALUES (100, '南特的雅克·德米', '剧情', '法国1991年有”法国电影新浪潮祖母“之称的艾格尼丝.瓦达(《拾穗者与我》)执导的人物记录片，是对其丈夫、法国著名导演雅克德米(《秋水伊人》《柳眉花娇》)的一次生平记录。', '阿涅斯·瓦尔达', '1991-05-15', 9.1, 500, 'Philippe Maron / Edouard Joubeaud / Laurent Monnier / Brigitte De Villepoix / Daniel Dublet', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2552495254.webp', '法国');
INSERT INTO `film` VALUES (101, '末代皇帝', '传记', '溥仪（尊龙 饰）的一生在电影中娓娓道来。他从三岁起登基，年幼的眼光中只有大臣身上的一只蝈蝈，江山在他心中只是一个不明所以的名词。长大了，他以为可以变革，却被太监一把烧了朝廷账本。他以为是大清江山的主人，却做了日本人的傀儡。', '贝纳尔多·贝托鲁奇', '1987-10-04', 9.3, 450, '尊龙 / 陈冲 / 邬君梅 / 彼得·奥图尔 / 英若诚', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p452089833.webp', '英国');
INSERT INTO `film` VALUES (102, '世界滞在记：18岁的小栗旬在西伯利亚', '传记', '18岁的小栗旬因为对前途的迷茫参加了这次西伯利亚之旅。在冬季的贝加尔湖上凿冰钓鱼，亲手宰杀猎到的小鹿，在这里他体验到了生活的艰辛，又再次重新思考了自己的道路。08年节目组再次回访，小栗旬说某种意义上这次旅行成为了他的原点。', '小栗旬', '2009-01-09', 9.3, 350, '小栗旬', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2238186336.webp', '日本');
INSERT INTO `film` VALUES (103, '钢琴家', '传记', '史标曼（艾德里安•布洛迪 Adrien Brody 饰）是波兰一家电台的钢琴师。二战即将爆发之时，他们全家被迫被赶进华沙的犹太区。在战争的颠沛流离中，家人和亲戚最终被纳粹杀害，而标曼本人也受尽种种羞辱和折磨，他侥幸得到一位朋友的帮助，暂时有了藏身之处。', '罗曼·波兰斯基', '2002-05-24', 9.2, 450, '艾德里安·布洛迪 / 托马斯·克莱舒曼 / 艾米莉娅·福克斯 / 米哈乌·热布罗夫斯基 / 埃德·斯托帕德', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p792376093.webp', '法国');
INSERT INTO `film` VALUES (104, '南海十三郎', '传记', '开片是说书人因聚众滋事，被警察（黄霑 饰）带到了警局问话，借说书人之口讲述了粤剧金牌编剧——南海十三郎艺海浮沉的一生。作为江太史公的十三子，江誉镠（谢君豪 饰）自由顽皮，出入名流场所。一次偶然的舞会，他遇到了上海的千金小姐莉莉（吴绮莉 饰），然而双方有缘相逢，无 份结亲。后来，他跟随她来到上海，竟落得穷困潦倒。', '谢君豪', '2018-03-14', 9.2, 600, '谢君豪', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2578760496.webp', '中国香港');
INSERT INTO `film` VALUES (105, '剃头匠', '传记', '敬大爷如今是个九十三岁高龄的耄耋老人，他有八十多年的剃头经历，至今仍住在北京胡同的大杂院里，过着北京城内最底层最普通也是最平淡的生活，他经常给老主顾们上门剃头、聊天，回家后拨弄着自己那座每天慢五分钟的老座钟，他希望每个人（也包括他自己）干干净净的来到人世，也希望人们干干净净利利索索的离去……', '哈斯朝鲁', '2006-10-24', 9.2, 350, '靖奎', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2186918733.webp', '中国大陆');
INSERT INTO `film` VALUES (106, '演员工作室：凯文·史派西', '传记', '演员工作室：凯文·史派西 Inside the Actors Studio - Kevin Spacey (2000)', '凯文·史派西', '2000-07-02', 5.2, 200, '詹姆斯·里普顿 / 凯文·史派西', 'https://images.weserv.nl/?url=img9.doubanio.com/view/subject/l/public/s3153676.jpg', '美国');
INSERT INTO `film` VALUES (107, '当幸福来敲门', '传记', '克里斯•加纳（威尔·史密斯 Will Smith 饰）用尽全部积蓄买下了高科技治疗仪，到处向医院推销，可是价格高昂，接受的人不多。就算他多努力都无法提供一个良好的生活环境给妻儿，妻子（桑迪·牛顿 Thandie Newton 饰）最终选择离开家。从此他带着儿子克里斯托夫（贾登·史密斯 Jaden Smith 饰）相依为命。', '加布里埃莱·穆奇诺', '2008-01-17', 9.1, 1000, '威尔·史密斯 / 贾登·史密斯 / 坦迪·牛顿 / 布莱恩·豪威 / 詹姆斯·凯伦 ', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2614359276.webp', '美国');
INSERT INTO `film` VALUES (108, '莫娣', '传记', '真人真事改编，描述在加拿大美丽的大西洋省份新斯科舍省（Nova Scotia），一位患有关节炎的民间艺术家莫娣·刘易斯(Maud Lewis)，对艺术不懈的追求，与她的丈夫相识，并以艺术、贩卖作品为生的励志生活。', '艾斯林·沃什', '1991-05-15', 9.1, 300, '莎莉·霍金斯 / 伊桑·霍克 / 卡瑞·玛切特 / 加布里埃尔·罗斯 / 扎卡里·贝内特', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2431089276.webp', '爱尔兰');
INSERT INTO `film` VALUES (109, '南特的雅克·德米', '剧情', '法国1991年有”法国电影新浪潮祖母“之称的艾格尼丝.瓦达(《拾穗者与我》)执导的人物记录片，是对其丈夫、法国著名导演雅克德米(《秋水伊人》《柳眉花娇》)的一次生平记录。', '阿涅斯·瓦尔达', '1991-05-15', 9.1, 600, 'Philippe Maron / Edouard Joubeaud / Laurent Monnier / Brigitte De Villepoix / Daniel Dublet', 'https://images.weserv.nl/?url=img9.doubanio.com/view/photo/s_ratio_poster/public/p2552495254.webp', '法国');
INSERT INTO `film` VALUES (110, '久石让在武道馆：与宫崎骏动画一同走过的25年', '纪录片', '《久石譲in武道馆 ～宫崎アニメと共に歩んだ25年间～》于08年8月5日在日本武道馆举行。曲目全部取材于25年来为宫崎骏动画写的配乐，并由久石让亲自上台指挥和弹奏，配以200人交响乐团和800人的合唱团，份量十足。', '久石让', '2008-08-05', 9.7, 450, '久石让', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2163632289.webp', '日本');
INSERT INTO `film` VALUES (111, '摩登家庭：摩登式告别', '纪录片', '《摩登告别》是一部长达一个小时的纪录片，回顾了《摩登家庭》11年来的发展历程，从剧本创作、选角、试播到大结局的解读，无一不在其中。这部纪录片通过对演职人员的独家专访，回顾了《摩登家庭》的起源故事，回顾了这部影响深远、深受观众喜爱的剧集取得的空前成功，并重温了许多感人至深的搞笑瞬间。', '克里斯托弗·威尔恰', '2020-04-08', 9.7, 1000, '索菲娅·维加拉 / 艾德·奥尼尔 / 泰·布利尔 / 朱丽·鲍温 / 艾瑞克·斯通斯崔特', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2594945703.webp', '美国');
INSERT INTO `film` VALUES (112, '地球脉动2：奇迹世界', '纪录片', '行星地球第二季精彩集锦', '大卫·爱登堡', '2017-01-01', 9.7, 650, '大卫·爱登堡', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2508258590.webp', '英国');
INSERT INTO `film` VALUES (113, '关口知宏之中国铁道大纪行 全集附特典', '纪录片', '《关口知宏之中国铁道大纪行》，该纪录片分为“春季篇”和“秋季篇”两部分，于NHK旗下的NHKhBShi高清频道播放。“春季篇”于2007年4月8日至6月10日间播放，而“秋季篇”则于9月2日至11月18日间播放。纪录片播出后在日本国内引起强烈反响。本片还出版了DVD。', '关口知宏', '2007-03-14', 9.7, 250, '关口知宏', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2561076037.webp', '日本');
INSERT INTO `film` VALUES (114, '披头士精选辑', '纪录片', '披头士精选辑 The Beatles Anthology (1995)', '鲍勃·斯米顿 / Geoff Wonfor / 凯文·戈德利', '1995-11-26', 9.7, 450, '保罗·麦卡特尼 / 乔治·哈里逊 / 林哥·斯塔尔 / 约翰·列侬', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2575300760.webp', '英国');
INSERT INTO `film` VALUES (115, '巴赫－哥德堡变奏曲 / 古尔德录音室演奏版录像', '纪录片', 'Prepared, shot, and edited over a period of five years from 1976 to 1981, the three-part series Glenn Gould Plays Bach has so far only been seen via the limited parameters of television transmission. ', '布鲁诺·蒙桑容', '1981-11-26', 9.7, 650, '格伦·古尔德', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2545772438.webp', '美国');
INSERT INTO `film` VALUES (116, 'KinKi Kids 你不在身边的夏天 songs', '爱情', 'KinKi Kids在2017年迎来了20周年的纪念日，但是在这个难忘的日子里，成员之一的堂本刚在夏天患上了突发性失聪。这样的二人是如何相互扶持，为粉丝们带来了难忘的715纪念演唱会，又是带着怎样的心情写下了这个夏天的纪念曲《Topaz Love》呢？', 'nhk songs', '2017-12-14', 9.7, 550, '堂本刚 / 堂本光一 / 近畿小子', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2507748550.webp', '日本');
INSERT INTO `film` VALUES (117, '卡拉扬指挥柏林爱乐乐团：贝多芬第九交响曲“合唱”', '纪录片', '01 不太快的，有些庄严的快板\r\n　　02 活泼的快板\r\n　　03 如歌的柔板－中速的行板－柔板\r\n　　04 急板－不太快的快板－很快的快板－急板－很快的快板－活泼的，进行曲式的快板－庄严的行板－始终充满生机的快板－不太过分的快板－适度的柔板－极快的急板', '赫伯特·冯·卡拉扬', '1968-04-17', 9.7, 450, '赫伯特·冯·卡拉扬 / Berliner Philharmoniker / Gundula Janowitz / Christa Ludwig / Jess Thomas', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2562676030.webp', '德国');
INSERT INTO `film` VALUES (118, '盗梦空间', '科幻', '道姆·柯布（莱昂纳多·迪卡普里奥 Leonardo DiCaprio 饰）与同事阿瑟（约瑟夫·戈登-莱维特 Joseph Gordon-Levitt 饰）和纳什（卢卡斯·哈斯 Lukas Haas 饰）在一次针对日本能源大亨齐藤（渡边谦 饰）的盗梦行动中失败，反被齐藤利用。', '克里斯托弗·诺兰', '2010-09-01', 9.3, 890, ' 莱昂纳多·迪卡普里奥 / 约瑟夫·高登-莱维特 / 艾利奥特·佩吉 / 汤姆·哈迪 / 渡边谦', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2616355133.webp', '美国');
INSERT INTO `film` VALUES (119, '星际穿越', '科幻', '近未来的地球黄沙遍野，小麦、秋葵等基础农作物相继因枯萎病灭绝，人类不再像从前那样仰望星空，放纵想象力和灵感的迸发，而是每日在沙尘暴的肆虐下倒数着所剩不多的光景。在家务农的前NASA宇航员库珀（马修·麦康纳 Matthew McConaughey 饰）接连在女儿墨菲（麦肯吉·弗依 Mackenzie Foy 饰）的书房发现奇怪的重力场现象，随即得知在某个未知区域内前NASA成员仍秘密进行一个拯救人类的计划。', '克里斯托弗·诺兰', '2014-11-12', 9.3, 900, '马修·麦康纳 / 安妮·海瑟薇 / 杰西卡·查斯坦 / 麦肯吉·弗依 / 卡西·阿弗莱克 ', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2614988097.webp', '美国');
INSERT INTO `film` VALUES (120, '楚门的世界', '科幻', '楚门（金•凯瑞 Jim Carrey 饰）是一个平凡得不能再平凡的人，除了一些有些稀奇的经历之外——初恋女友突然失踪、溺水身亡的父亲忽然似乎又出现在眼前，他和绝大多数30多岁的美国男人绝无异样。这令他倍感失落。他也曾试过离开自己生活了多年的地方，但总因种种理由而不能成行。', '彼得·威尔', '1998-06-05', 9.3, 850, '金·凯瑞 / 劳拉·琳妮 / 艾德·哈里斯 / 诺亚·艾默里奇 / 娜塔莎·麦克艾霍恩', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p479682972.webp', '美国');
INSERT INTO `film` VALUES (121, '机器人总动员', '科幻', '公元2805年，人类文明高度发展，却因污染和生活垃圾大量增加使得地球不再适于人类居住。地球人被迫乘坐飞船离开故乡，进行一次漫长无边的宇宙之旅。临行前他们委托Buynlarge的公司对地球垃圾进行清理，该公司开发了名为WALL·E（Waste Allocation Loa d Lifters – Earth 地球废品分装员）的机器人担当此重任。', '安德鲁·斯坦顿', '2008-06-27', 9.3, 850, '本·贝尔特 / 艾丽莎·奈特 / 杰夫·格尔林 / 佛莱德·威拉特 / 西格妮·韦弗', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p1461851991.webp', '美国');
INSERT INTO `film` VALUES (122, '蝙蝠侠：黑暗骑士', '科幻', '从亲眼目睹父母被人杀死的阴影中走出来的“蝙蝠侠”，经历了成长之后，已经不再是那个桀骜不的孤单英雄了。在警官吉姆·戈登和检查官哈维·登特的通力帮助下，“蝙蝠侠”无后顾之忧地继续满世界的奔波，与日益增长起来的犯罪威胁做着永无休止的争斗，而他所在的高谭市，也是进展最为明显的地方，犯罪率以一种惊人的速度持续下降着，毕竟对方是能够上天入地的“蝙蝠侠”，不借两个胆子谁还敢造次呢？', '克里斯托弗·诺兰', '2008-07-14', 9.2, 900, '克里斯蒂安·贝尔 / 希斯·莱杰 / 艾伦·艾克哈特 / 迈克尔·凯恩 / 玛吉·吉伦哈尔 ', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p462657443.webp', '美国');
INSERT INTO `film` VALUES (123, '超感猎杀：完结特别篇', '剧情', 'Netfilx宣布将为月初被砍的《超感猎杀》制作两小时最终篇！Wolfgang的命运及更多大坑终于要填上啦！剧集制作人拉娜·沃卓斯基在致Sense8家族的一封信中感谢全球粉丝，表示大结局正在制作中，将于明年上线！', '拉娜·沃卓斯基', '2018-06-08', 9.2, 600, '裴斗娜 / 杰米·克莱顿 / 蒂娜·德赛 / 塔彭丝·米德尔顿 / 马克思·雷迈特', 'https://images.weserv.nl/?url=img3.doubanio.com/view/photo/s_ratio_poster/public/p2520264840.webp', '美国');
INSERT INTO `film` VALUES (124, '黑镜：圣诞特别篇', '科幻', '圣诞节将至，一间地处偏远的小木屋里，波特（拉菲·斯波 Rafe Spall 饰）和马特（乔恩·哈姆 Jon Hamm 饰）同坐一桌，用红酒和烤土豆庆祝这个银装素裹的节日。波特沉默寡言，无精打采，而马特却恰恰相反，为了逗波特讲话，他向波特讲述了自己的过去。', '卡尔·蒂贝茨', '2014-12-16', 9.1, 450, '乔恩·哈姆 / 拉菲·斯波 / 奥娜·卓别林 / 娜塔丽·特纳 / 詹妮特·蒙哥马利', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2233676442.webp', '英国');
INSERT INTO `film` VALUES (125, '攻壳机动队2：无罪', '科幻', '草薙素子之后，巴特与侦探出身的陀古萨结为搭档。近期发生多起机器人偶杀害主人继而自杀的事件，由于受害者家属均无公诉，且死者中有政客与公安官员，于是公安9课派出巴特小组调查此案。杀人人偶皆为荒凉地带公司出品的哈德莉机型，应部分顾客要求，该机型同时具备异性玩伴的功能，巴特从荒凉地带公司出货官遇害入手，卷入与黑帮的战斗，期间有人入侵他的大脑，使其自残。', '押井守', '2004-03-06', 9.1, 600, '田中敦子 / 大塚明夫 / 山寺宏一 / 大木民夫 / 仲野裕', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p1910832189.webp', '日本');
INSERT INTO `film` VALUES (126, '大都会', '科幻', 'Freder（Gustav Fröhlich 饰）是大都会主宰 Joh Fredersen（Alfred Abel 饰）的儿子。经一位圣洁姑娘（Brigitte Helm 饰）启示，Freder 来到地下目睹了在此劳作的劳工们悲惨的境遇。Freder 向父亲进言，想改变劳工们的处境。但 Joh 不为所动，却对从劳工们身上发现的地图感到忧虑。', '弗里茨·朗', '1927-01-10', 9.1, 800, '阿弗莱德·阿贝尔 / 古斯塔夫·佛力施 / 布里吉特·赫尔姆 / 鲁道夫·克莱恩-鲁格', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p906689323.webp', '德国');
INSERT INTO `film` VALUES (127, '赛文奥特曼 我是地球人', '科幻', '在幾百萬年前，地球原本是外星人的故鄉，人類殘暴的祖先在地球進行殺戳把這地方鵲巢鳩佔。而世代以來，所有統治者還一直把紀錄了這個秘密的「亞米加檔案」禁敝起來，不肯承認過錯。事實上，外星人直對地球虎視眈眈，並非因為要侵略，而是想討回公道。', '神澤信一 / 満留浩昌', '1999-12-31', 9.1, 500, '南条弘二 / 山崎勝之 / 正岡邦夫 / 古賀亘 / 鵜川薫', 'https://images.weserv.nl/?url=img2.doubanio.com/view/photo/s_ratio_poster/public/p2547616522.webp', '日本');
INSERT INTO `film` VALUES (128, '新世纪福音战士 第0:0话 诞生之始', '科幻', '新世紀エヴァンゲリオンGenesis0:0　・ビデオ・ＬＤ 発売に先駆けて作られた特別先行編です', '庵野秀明', '1995-12-21', 9.1, 400, '绪方惠美 / 林原惠美 / 三石琴乃 / 宫村优子', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2560431118.webp', '日本');
INSERT INTO `film` VALUES (129, '少年骇客：变身之谜', '动作', '【内容简介】\r\n　　就在田小班與董悟博士戰鬥之時，一道不明光線啟動了Omnitrix的自毀模式，而鑽金剛在收到訊號之後來到地球，與小班會合之後，來到外太空尋找Omnitrix的發明者，以阻止自毀模式繼續運行，危害宇宙安全！', 'Greg Klein', '2007-08-10', 9.1, 350, '塔拉·斯特朗 / 梅根·史密斯 / 保罗·伊丁', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p2320482809.webp', '美国');
INSERT INTO `film` VALUES (130, '黑客帝国', '动作', '不久的将来，网络黑客尼奥（基奴李维斯 饰）对这个看似正常的现实世界产生了怀疑。他结识了黑客崔妮蒂（凯莉·安·摩丝 饰），并见到了黑客组织的首领墨菲斯（劳伦斯·菲什伯恩 饰）。墨菲斯告诉他，现实世界其实是由一个名叫“母体”的计算机人工智能系统控制，人们就像他们饲养的动物，没有自由和思想，而尼奥就是能够拯救人类的救世主。', '莉莉·沃卓斯基 / 拉娜·沃卓斯基', '1999-03-31', 9.0, 900, '基努·里维斯 / 劳伦斯·菲什伯恩 / 凯瑞-安·莫斯 / 雨果·维文 / 格洛丽亚·福斯特 ', 'https://images.weserv.nl/?url=img1.doubanio.com/view/photo/s_ratio_poster/public/p451926968.webp', '美国');
INSERT INTO `film` VALUES (131, 'javaee大电影', '剧情', 'javaEE大电影，在线影评系统。', '王亚光', '2020-12-15', 10.0, 124, '流星雨 吴雨双', 'https://filmcomment.oss-cn-chengdu.aliyuncs.com/2020/12/17/767f10df758c445d9d0cb948921d0685file.png', '中国大陆');
INSERT INTO `film` VALUES (132, '测试时间', '犯罪', '测试电影', '是是是', '2020-12-15', 3.0, 25, '三大法师', 'https://filmcomment.oss-cn-chengdu.aliyuncs.com/2020/12/17/feefa1bf8f5b467c819ebe66dab98f93file.png', '中国香港');
INSERT INTO `film` VALUES (133, '测试日期', '犯罪', '烘干机规划局', '会改变经历过后', '2020-12-15', 4.0, 556, '刚放假', '', '德国');
INSERT INTO `film` VALUES (134, '又是一次测试', '动作', '水电费股东会', '天原集团和', '2020-12-13', 3.0, 8, '房管局过户', 'https://filmcomment.oss-cn-chengdu.aliyuncs.com/2020/12/17/33698480c6714f5abfe7505e1ddbabecfile.png', '中国香港');

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`  (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `avatar` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `phone` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `gmt_create` date DEFAULT NULL,
  PRIMARY KEY (`uid`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of user
-- ----------------------------
INSERT INTO `user` VALUES (1, 'admin', 'admin', 'https://i.loli.net/2020/09/30/1eSxqEml83d4U9A.png', '123@qq.com', '12345678', '2020-12-03');
INSERT INTO `user` VALUES (2, '王亚光', '123456', 'https://i.loli.net/2020/09/30/1eSxqEml83d4U9A.png', '1350216878@qq.com', '13032818127', '2020-12-05');
INSERT INTO `user` VALUES (3, 'string', 'string', 'https://i.loli.net/2020/09/30/1eSxqEml83d4U9A.png', 'string', 'string', '2020-12-08');
INSERT INTO `user` VALUES (4, 'string', 'string', 'https://i.loli.net/2020/09/30/1eSxqEml83d4U9A.png', 'string', '13032818129', '2020-12-08');
INSERT INTO `user` VALUES (5, '测试验证码', 'string', 'string', 'string', '13032818128', '2020-12-15');

SET FOREIGN_KEY_CHECKS = 1;
